#Deployment.yaml - tells Kubernetes how to run your Python app in containers.
#service.yaml - Tells Kubernetes how to expose your app so its accessible.
# A manifest is just a file written in YAML format that tells Kubernetes what you want it to do.

apiVersion: apps/v1
kind: Deployment
metadata:
  name: python-app
  labels:
    app: python-app
spec:
  replicas: 2
  selector:
    matchLabels:
      app: python-app
  template:
    metadata:
      labels:
        app: python-app
    spec:
      containers:
      - name: python-app
        image: my-python-app:latest
        ports:
        - containerPort: 5000
