#Step 3.0. 
#Getting started to understand Workflow via workflow syntax docs.
#SET UP GITHUT  SECRETS

#Step 3.1 - Defines name of the pipeline & When to trigger (e.g push on main).
name: Build & Reploy

on:
    push:
        branches: [main]

#Step 3.2 - Defining job environment machine for Github Actions to run on. 
jobs:
    docker-build-push:
        runs-on: ubuntu latest

#step 3.3 Checkout the repo for github to fetch code to build & deploy.
        steps:
            - name: Checkout Code
              uses: actions/checkout@v3

#Steps 3.4 - Checkout the repo for Docker BuildX to build multi-platform Docker Images - more powerful & flexible. 
            - name: Set up Docker Buildx
              uses: dockersetup-buildx-action@v2